# Generated by Django 5.2.4 on 2025-08-06 06:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProtectedProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(unique=True)),
                ("name", models.CharField(max_length=100)),
                ("age", models.PositiveIntegerField()),
                ("sex", models.CharField(choices=[("남", "남"), ("여", "여")])),
                ("guardian", models.BooleanField(default=False)),
                ("preferred_location", models.CharField(blank=True)),
                ("budget_min", models.PositiveBigIntegerField(blank=True)),
                ("budget_max", models.PositiveBigIntegerField(blank=True)),
                ("preferred_services", models.TextField(blank=True)),
                ("health_conditions", models.TextField(blank=True)),
                ("additional_info", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="protected_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SelfProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kakao_id", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("scrapped", models.BooleanField(default=False)),
                ("recent", models.BooleanField(default=False)),
                ("reviews", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="self_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
