# Generated by Django 5.2.4 on 2025-08-06 06:59

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="protectedprofile",
            name="additional_info",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="protectedprofile",
            name="budget_max",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="protectedprofile",
            name="budget_min",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="protectedprofile",
            name="health_conditions",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="protectedprofile",
            name="name",
            field=models.CharField(
                max_length=100, validators=[myapp.models.validate_korean_only]
            ),
        ),
        migrations.AlterField(
            model_name="protectedprofile",
            name="number",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="protectedprofile",
            name="preferred_location",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="protectedprofile",
            name="preferred_services",
            field=models.TextField(blank=True, null=True),
        ),
    ]
