# Generated by Django 5.2.4 on 2025-08-06 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_alter_protectedprofile_additional_info_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="protectedprofile",
            name="guardian",
            field=models.CharField(choices=[("유", "유"), ("무", "무")]),
        ),
        migrations.AlterField(
            model_name="protectedprofile",
            name="preferred_location",
            field=models.TextField(blank=True, null=True),
        ),
    ]
