# Generated by Django 5.2.4 on 2025-08-06 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_alter_protectedprofile_guardian_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="protectedprofile",
            name="guardian",
            field=models.CharField(choices=[("유", "유"), ("무", "무")], default="무"),
        ),
        migrations.AlterField(
            model_name="protectedprofile",
            name="sex",
            field=models.CharField(choices=[("남", "남"), ("여", "여")], default="남"),
        ),
    ]
