# Generated by Django 5.2.4 on 2025-08-07 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_alter_protectedprofile_guardian_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="protectedprofile",
            old_name="preferred_location",
            new_name="address",
        ),
        migrations.AlterField(
            model_name="protectedprofile",
            name="number",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
