# Generated by Django 5.2.4 on 2025-08-07 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_rename_preferred_location_protectedprofile_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="protectedprofile",
            name="address_detail",
            field=models.TextField(blank=True, null=True),
        ),
    ]
