# Generated by Django 5.2.4 on 2025-08-08 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0006_protectedprofile_address_detail"),
    ]

    operations = [
        migrations.CreateModel(
            name="SilverCareFacility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "facility_name",
                    models.CharField(max_length=200, verbose_name="시설명"),
                ),
                (
                    "institution_type",
                    models.CharField(max_length=100, verbose_name="기관유형"),
                ),
                ("address", models.CharField(max_length=255, verbose_name="주소")),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="전화번호"
                    ),
                ),
                (
                    "homepage",
                    models.URLField(blank=True, null=True, verbose_name="홈페이지"),
                ),
                (
                    "designation_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="장기요양기관지정일"
                    ),
                ),
                (
                    "transportation",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="교통편"
                    ),
                ),
                (
                    "parking_facility",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="주차시설"
                    ),
                ),
                ("capacity", models.IntegerField(default=0, verbose_name="정원")),
                (
                    "current_male",
                    models.IntegerField(default=0, verbose_name="현원(남)"),
                ),
                (
                    "current_female",
                    models.IntegerField(default=0, verbose_name="현원(여)"),
                ),
                (
                    "waiting_male",
                    models.IntegerField(default=0, verbose_name="대기(남)"),
                ),
                (
                    "waiting_female",
                    models.IntegerField(default=0, verbose_name="대기(여)"),
                ),
                (
                    "caregiver_type1",
                    models.IntegerField(
                        default=0,
                        verbose_name="재가노인복지시설방문요양-요양보호사-1급",
                    ),
                ),
                (
                    "caregiver_type2",
                    models.IntegerField(
                        default=0,
                        verbose_name="재가노인복지시설방문요양-요양보호사-2급",
                    ),
                ),
                (
                    "caregiver_suspended",
                    models.IntegerField(
                        default=0,
                        verbose_name="재가노인복지시설방문요양-요양보호사-유예",
                    ),
                ),
                (
                    "longterm_caregiver_type1",
                    models.IntegerField(
                        default=0,
                        verbose_name="재가장기요양기관방문요양-요양보호사-1급",
                    ),
                ),
                (
                    "longterm_caregiver_type2",
                    models.IntegerField(
                        default=0,
                        verbose_name="재가장기요양기관방문요양-요양보호사-2급",
                    ),
                ),
                (
                    "longterm_caregiver_suspended",
                    models.IntegerField(
                        default=0,
                        verbose_name="재가장기요양기관방문요양-요양보호사-유예",
                    ),
                ),
                ("nurse", models.IntegerField(default=0, verbose_name="간호사")),
                (
                    "nursing_assistant",
                    models.IntegerField(default=0, verbose_name="간호조무사"),
                ),
                ("contract", models.IntegerField(default=0, verbose_name="계약")),
                ("manager", models.IntegerField(default=0, verbose_name="관리인")),
                (
                    "physical_therapist",
                    models.IntegerField(default=0, verbose_name="물리치료사"),
                ),
                ("assistant", models.IntegerField(default=0, verbose_name="보조원")),
                (
                    "general_manager",
                    models.IntegerField(default=0, verbose_name="사무국장"),
                ),
                ("office", models.IntegerField(default=0, verbose_name="사무실")),
                (
                    "office_worker",
                    models.IntegerField(default=0, verbose_name="사무원"),
                ),
                (
                    "social_worker",
                    models.IntegerField(default=0, verbose_name="사회복지사"),
                ),
                (
                    "washing_room",
                    models.IntegerField(default=0, verbose_name="세면/세탁실"),
                ),
                (
                    "head_of_facility",
                    models.IntegerField(default=0, verbose_name="시설장"),
                ),
                ("nutritionist", models.IntegerField(default=0, verbose_name="영양사")),
                (
                    "sanitation_worker",
                    models.IntegerField(default=0, verbose_name="위생원"),
                ),
                ("suspended", models.IntegerField(default=0, verbose_name="유예")),
                (
                    "occupational_therapist",
                    models.IntegerField(default=0, verbose_name="작업치료사"),
                ),
                (
                    "day_night_care",
                    models.IntegerField(
                        default=0, verbose_name="재가노인복지시설주야간보호"
                    ),
                ),
                ("cook", models.IntegerField(default=0, verbose_name="조리원")),
                ("bedroom", models.IntegerField(default=0, verbose_name="침실")),
                ("toilet", models.IntegerField(default=0, verbose_name="화장실")),
            ],
            options={
                "verbose_name": "실버케어 시설",
                "verbose_name_plural": "실버케어 시설 목록",
            },
        ),
    ]
